#ifndef _INC_UNITTETST_TESTSTATICRINGBUF_VERIFY_TS_0001_TestData_H
#define _INC_UNITTETST_TESTSTATICRINGBUF_VERIFY_TS_0001_TestData_H

#include "Common/datatypes.h"

#define RB_LENGTH   10

#define BYTEARRAY0_ITEMS_COUNT 24

#endif // !_INC_UNITTETST_TESTSTATICRINGBUF_VERIFY_TS_0001_TestData_H
